### ISSUE TITLE
Exports are not thread-safe, causes crash when handling multiple streams at once

### ISSUE THREAD

**Issue by KaleidonKep99** [BlackMIDIDevs/xsynth-clib#4]
As the title says, spawning more than one rendering thread and working on both simultaneously will cause a segfault.

I have no idea why it's referencing a Realtime function there.

![2024 08 02 @ 11 36 05 PM (OccasionalMitea77e092c476428d2)](https://github.com/user-attachments/assets/4ef95237-adb1-4226-a7dc-b7bb5b8c3f7f)
![cfba67b5df2fa1b9ce8b1c9cca759185](https://github.com/user-attachments/assets/0a4c284a-5f80-406d-9556-4b4f7a4bc65f)

**Comment by MyBlackMIDIScore** [comment]
Hmm I just tried rendering two MIDIs simultaneously and it worked as expected. Btw it says `Group does not exist.` as the panic error so OC is calling a ReadSamples function with a nonexistent ID/handle. Although I really have no idea why the realtime function is mentioned there...
Question, are you creating a new channel group on the same instance of the library for each MIDI, or you load a new instance altogether?

**Comment by KaleidonKep99** [comment]
> Hmm I just tried rendering two MIDIs simultaneously and it worked as expected. Btw it says `Group does not exist.` as the panic error so OC is calling a ReadSamples function with a nonexistent ID/handle. Although I really have no idea why the realtime function is mentioned there... Question, are you creating a new channel group on the same instance of the library for each MIDI, or you load a new instance altogether?

The process is as follows:

1. Initialize the "XSynthEngine" class.
    1. Generate default stream params and group options, and fill the variables with the required information.
    2. Initialize the SoundFont handles, to be able to share them across multiple streams to save up on memory.
    3. Allocate a nint (raw pointer to array) for the list of SoundFont handles, so that we can pass it to XSynthRenderer later.
2. Initialize the "XSynthRenderer" class for each MIDI/track thread.
    1. Create a channel group using the information we set up in XSynthEngine.
    2. Store the handle of the channel group on a variable called "handle".
    3. Set the amount of layers.
    4. Set the SoundFonts by using the nint we set up in XSynthEngine.
    5. Set the stream params using the StreamParams that we set up in XSynthEngine.
    6. After the initialization is done, begin calling ReadSamples by passing the handle we stored earlier.

**Comment by MyBlackMIDIScore** [comment]
Hmm interesting, so you are using a single instance of the library for everything. The error was a bit weird though because it meant that it searched for the handle and it did not exist, so either the group wasn't created properly or the handle got corrupt or idk what.

Also as I said I cannot recreate this, so could you share the exact setup you used to get this error?

I do have in mind a potential fix but it will help a lot better if I can recreate the error to debug it.

**Comment by KaleidonKep99** [comment]
> Hmm interesting, so you are using a single instance of the library for everything. The error was a bit weird though because it meant that it searched for the handle and it did not exist, so either the group wasn't created properly or the handle got corrupt or idk what.
> 
> Also as I said I cannot recreate this, so could you share the exact setup you used to get this error?
> 
> I do have in mind a potential fix but it will help a lot better if I can recreate the error to debug it.

I pushed the latest changes on the repo, you can pull if you want.

The group is created properly though, because I double-check, triple-check even to see if it's valid.

**Comment by MyBlackMIDIScore** [comment]
Alright I managed to get the error when using per track rendering. I will look into this more tomorrow and I'll let you know. It seems like a pretty complex issue.

**Comment by MyBlackMIDIScore** [comment]
I just tried a potential fix and it worked fine in some tests I did. I made a commit in the `thread-safety` branch so you can try it out. Let me know if it works.

**Comment by KaleidonKep99** [comment]
I'll test it now, thanks!

**Comment by KaleidonKep99** [comment]
Ok, it seems to work, but it is *excruciatingly* slow, even when the thread pool is disabled...

**Comment by MyBlackMIDIScore** [comment]
> Ok, it seems to work, but it is _excruciatingly_ slow, even when the thread pool is disabled...

Oof I was afraid something like that might happen. You see the current way of making it thread safe was to only allow one thread at a time access the channel group array. So basically this means that only *one* channel group is allowed to write at any given time, while all others are waiting for it to finish.

I'll probably have to think of some other approach to this.

When rendering one MIDI only the performance is the same?

**Comment by KaleidonKep99** [comment]
> > Ok, it seems to work, but it is _excruciatingly_ slow, even when the thread pool is disabled...
> 
> Oof I was afraid something like that might happen. You see the current way of making it thread safe was to only allow one thread at a time access the channel group array. So basically this means that only _one_ channel group is allowed to write at any given time, while all others are waiting for it to finish.
> 
> I'll probably have to think of some other approach to this.
> 
> When rendering one MIDI only the performance is the same?

I think the best approach would be to give the programmer direct access to a XSynth Channel Group instance, instead of hiding it behind the clib interface, so that they can manage the creation and disposal of the object.

After all, I know when an instance exists because I initialized it and I am actively hitting it with data up until its disposal, and nothing else outside of the working thread can access it.

**Comment by MyBlackMIDIScore** [comment]
> I think the best approach would be to give the programmer direct access to a XSynth Channel Group instance, instead of hiding it behind the clib interface, so that they can manage the creation and disposal of the object.

That would be ideal and it is actually how the Rust lib works, but I am unsure how exactly to do something like that in the C bindings. Since a ChannelGroup in XSynth is basically a class (Rust struct) and I don't really know how to directly export it to C/C++ to be managed by the user. I'll try to think of a way to do it though.

Is this how BASS does it too?

**Comment by KaleidonKep99** [comment]
> > I think the best approach would be to give the programmer direct access to a XSynth Channel Group instance, instead of hiding it behind the clib interface, so that they can manage the creation and disposal of the object.
> 
> That would be ideal and it is actually how the Rust lib works, but I am unsure how exactly to do something like that in the C bindings. Since a ChannelGroup in XSynth is basically a class (Rust struct) and I don't really know how to directly export it to C/C++ to be managed by the user. I'll try to think of a way to do it though.
> 
> Is this how BASS does it too?

Nope, BASS does what XSynth does now, it just returns a HSTREAM handle to pass to any of the functions that interact with it.

**Comment by MyBlackMIDIScore** [comment]
I just made a new commit in the branch, tell me if the performance is better when you try it. (And if it works obviously)

**Comment by MyBlackMIDIScore** [comment]
@KaleidonKep99 Btw I also just made [another commit](https://github.com/BlackMIDIDevs/xsynth-clib/commit/5eee829404bcabb83bf87df4c2b7c250b648a1b3) on the `thread-safety` branch, which instead of IDs you get a pointer to the created instance of ChannelGroup/Soundfont/RealtimeSynth so it's completely up to the user how to handle stuff.

Let me know if this works better for you than the [previous commit](https://github.com/BlackMIDIDevs/xsynth-clib/commit/65dc22b53f2a3531d0b5dc2b47e592ab98d1f81d) I mentioned above.

**Comment by KaleidonKep99** [comment]
Ok, I'll let you know if I find issues with the new update.

**Comment by MyBlackMIDIScore** [comment]
> Ok, I'll let you know if I find issues with the new update.

Btw if you want to try it now, I'd suggest you wait a few minutes for me to push another commit which makes those pointers/handles more legible

**Comment by KaleidonKep99** [comment]
I am not sure what's going on here? I need to use structs that reference other unpopulated structs? C# is not liking this one bit.

![image](https://github.com/user-attachments/assets/eaabcd2a-20cf-4790-8991-6aaf78738606)
![image](https://github.com/user-attachments/assets/65d80f09-1ead-4cbc-8085-bf82cc155640)

**Comment by MyBlackMIDIScore** [comment]
`ChannelGroup`, `Arc_SampleSoundfont` and `RealtimeSynth` are not meant to be used by the user. I still have to think of a way to possibly hide those but Rust wouldn't let me do it the way I had it in mind.

Anyway would something like that work?
![image](https://github.com/user-attachments/assets/c1415da8-fd73-4422-a543-8d302616e954)

Or maybe with `nint` instead of `void*` if they are the same thing idk

**Comment by KaleidonKep99** [comment]
I don't think issue https://github.com/BlackMIDIDevs/xsynth/issues/80 has been fixed yet...

https://github.com/user-attachments/assets/157e9fb8-d787-414f-bcaa-09558d90507b

BTW it works so far, but now aborting the conversion process consistently causes OCv2 to segfault, while before you had a 25-30% chance of encountering the error.
I'll trace the error down on my end, to see if I can make it so OCv2 waits for XSynth to be done, before deleting the channels.

**Comment by KaleidonKep99** [comment]
> > I don't think issue [BlackMIDIDevs/xsynth#80](https://github.com/BlackMIDIDevs/xsynth/issues/80) has been fixed yet...
> 
> Yeah the clib uses the `0.1.0` tag which does not include this commit, it will be included in a later tag. Currently you can fix by replacing `tag = "0.1.0"` with `rev = "62ed54b"` in `Cargo.toml`.
> 
> > BTW it works so far, but now aborting the conversion process consistently causes OCv2 to segfault, while before you had a 25-30% chance of encountering the error.
> > I'll trace the error down on my end, to see if I can make it so OCv2 waits for XSynth to be done, before deleting the channels.
> 
> Yeah this probably has to do with OC requesting to read after dropping a group. With the previous commit before I implement the pointers, I was getting panics from ReadSamples functions that the program was requesting groups that were removed (it was thread safe). Idk how BASS handles this but since you now have almost full control of the channel group object, OC should wait for all the render threads to finish before dropping the groups.

Oh yeah that seems to work!!!

I also fixed the random segfaults, I uploaded the changes to the repo if you wanna test.

**Comment by MyBlackMIDIScore** [comment]
Alright great! Will close this issue and make a few last changes to the API tomorrow before I merge into master (mostly about those unpopulated structs).

I'll also try the OC update, and possibly make a PR there for a few changes about XSynth.

**Comment by KaleidonKep99** [comment]
Small request, would it be possible to **completely** disable thread pooling?
I noticed that, even when it's disabled, XSynth still spawns 6-8 threads per channel group, causing the converter to stall (or worse, cause the PC to hang) when spawning more than 4-5 conversion threads.

**Comment by MyBlackMIDIScore** [comment]
> Small request, would it be possible to **completely** disable thread pooling? I noticed that, even when it's disabled, XSynth still spawns 6-8 threads per channel group, causing the converter to stall (or worse, cause the PC to hang) when spawning more than 4-5 conversion threads.
> 
> **EDIT**: Or, if that's not possible, have an extra option in the XSynth_GroupOptions that allows me to set the maximum amount of threads per channel group?

I am not sure if setting a limit on the threads will be possible but it is possible to add an option to disable pooling. I'd suggest you make an issue in the main XSynth repo about this so I can track it (because it is not related to the clib).
