### ISSUE TITLE
E0603: module 'config' is private

### ISSUE THREAD

**Issue by KaleidonKep99** [BlackMIDIDevs/xsynth-clib#8]
I can not compile xsynth-clib under Linux, complaining about how the module "config" is private.

![2024 08 06 @ 07 00 28 PM (AncientKawala5f4d012cf2e4d546)](https://github.com/user-attachments/assets/554f5625-1557-46e8-b5c2-9621597ed1b3)

**Comment by MyBlackMIDIScore** [comment]
What branch is this? Are you using the latest commit?
I just pushed the last changes with the pointer stuff into `master`. See if this works for you.

**Comment by KaleidonKep99** [comment]
Apparently reinstalling Rust fixed the issue... I think I broke it while I tried to get osxcross to work on my Linux server. Sorry!
